name: Package and push ontology to nuget.org

on:
  workflow_dispatch:
  release:
    types:
      - released
      - prereleased

env: 
  NUGET_FEED_URL: https://api.nuget.org/v3/index.json

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Configure package generation directory
        run: |
          mkdir build
          cp Metadata/Willow*.jsonld build/
          cp Metadata/*.nuspec build/
          cp Metadata/ReadMe.md build/
      - name: 'Run nuget pack'
        run: dotnet pack build/*.nuspec -o build
      - name: 'Publish to nuget.org'
        run: dotnet nuget push build/*.nupkg -s "${{ env.NUGET_FEED_URL }}" --skip-duplicate -k ${{ secrets.NUGET_API_KEY }} 